{% set name = "colomoto_jupyter" %}
{% set version = "0.4.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_rev: v{{ version }}
  git_url: https://github.com/colomoto/colomoto-jupyter.git

channels:
  - colomoto # for pydot
  - bioconda # for pygraphviz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - networkx >=2.0
    - pydot >=1.2.3
    - pygraphviz

about:
  home: https://github.com/colomoto/colomoto-jupyter
  summary: 'CoLoMoTo helper functions for Juypter integration'
  license_family: LGPL
  license: LGPL v3+/CeCILL-C

